### ISSUE TITLE
Using with vue.js

### ISSUE THREAD

**Issue by bmpeg** [matt-way/gifuct-js#10]
Hi,

I am trying to use gifuct-js with vue.js. I can't run the following example with Vue.js.

**https://stackoverflow.com/a/58405203**

**I did the installation as follows.**

npm install --save gifuct-js

**In Vue;**
import GIF from 'gifuct-js/dist/gifuct-js.js'

**I get the following error.**
Uncaught TypeError: gifuct_js_dist_gifuct_js_js__WEBPACK_IMPORTED_MODULE_12___default.a is not a constructor
    at XMLHttpRequest.xhr.onload

Thanks.

**Comment by matt-way** [comment]
Hi, Sorry for the late reply, I have just finished updating the lib to v2. Just waiting to get access to the npm account so I can push an update.

**Comment by matt-way** [comment]
Finally got npm access after all this time. Version is up. Sorry for the delay.
