### ISSUE TITLE
Decoder-bug when showing jblack.gif in the demo

### ISSUE THREAD

**Issue by tiptronic** [matt-way/gifuct-js#12]
There's a decoder bug (was also present in v1):

If I just want to play back the jblack.gif, I'm seeing this:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/80752/77458706-ec315c00-6dfe-11ea-9bad-ae74d094a903.png">

STR: 
- just load ./demo/index.html (I loaded it by double-clicking, ergo: using file:// protocol) (no difference when running http://)
- enter '../demo/jblack.gif' into the text-field
- 'Load'

MacOS 10.15.3 (19D76) - latest Chrome, Firefox DevEd, Safari

**Comment by groowyCZ** [comment]
I suspect that it's because the frames should be layered on top of each other
