### ISSUE TITLE
Npm download broken version

### ISSUE THREAD

**Issue by emericspiroux** [matt-way/gifuct-js#14]
Hi,

First thanks for this library, I didn't test it anymore but I got two weirds errors when I downloaded it through npm : Main inside package.json is wrong (I update it manually to make it work) but I've got error inside code...

I think you need to publish a new version to permit to npm to find the latest working version ! 

npm version : 1.0.0
current github repo version : 2.0.0

All is good for me, I download it directly from github but for next users it can be a good thing to do 👍 

Best regards !

**Comment by matt-way** [comment]
Finally got npm access fixed and updated :) Version should be there now.
