### ISSUE TITLE
Missing disposalType and delay on first frame of some GIFs

### ISSUE THREAD

**Issue by adam-perez** [matt-way/gifuct-js#18]
Hello.

First of all, thanks for your awesome work. I've been writing & maintaining JavaScript GIF players for years, and this is the smallest / fastest GIF parser I've come across so far.

I see that most of the developers of this package also maintain the  [jsBinarySchemeParser](https://github.com/matt-way/jsBinarySchemaParser) so I hope this is a fine place to create this issue.

Currently I'm writing a React GIF renderer built on top of this package. Through my testing I came across some GIFs that seem to have trouble parsing through the `jsBinarySchemeParser`.

![sunset](https://user-images.githubusercontent.com/5103947/103562069-192b9880-4e80-11eb-867b-30cd9834b11c.gif)
![nyancat](https://user-images.githubusercontent.com/5103947/103562082-1d57b600-4e80-11eb-94d8-d76e518806c5.gif)

They both seem to have the same problem, which is that the first frame in the return value [here](https://github.com/matt-way/gifuct-js/blob/bf0d783423c9cde64e83f86581e5442922beefe4/src/index.js#L82) does not have a `duration` or `disposalType`.

I assume every frame should have this information associated with it.

Regards,
Adam

**Comment by matt-way** [comment]
I'll test those gifs when I get a chance and get back to you.

**Comment by matt-way** [comment]
I've checked these out, and noticed that in the gif spec, the GCE is completely optional (the block that includes the duration and disposal type).

See: http://www.matthewflickinger.com/lab/whatsinagif/bits_and_bytes.asp#graphics_control_extension_block

My thinking is that to save space, whatever encoded the gifs above didn't deem the initial frames to require a GCE. I would take this possibly to mean the first frames are used as initial backgrounds with no delay, but I am not 100% sure. The main point though is that it looks like they are parsing fine using the lib.

**Comment by adam-perez** [comment]
Ahh, sorry for the misunderstanding. I'll admit that I haven't read most of the GIF spec 😅. Much thanks for looking into this. I'll try accounting for this anomaly in my renderer code.

**Comment by adam-perez** [comment]
Reopening because I'm having another issue with the sunset GIF. Your library seems to be filling the first frame's background color with black when it should be transparent. I split the GIF into frames using multiple online GIF splitters, and they're all showing the first frame as having a transparent background.

Since there's no transparent index on the frame, do you have any idea how I'm supposed to know that those black values are actually supposed to be transparent when you render them?

**Comment by matt-way** [comment]
As this is the first time I've seen the initial GCE omitted, my guess would be to always treat the first frames (or any frame for that matter) colour index as transparent if none exists.

**Comment by goforu** [comment]
any updates? no delay property on first frame
