### ISSUE TITLE
Issues with few Giphy GIFs

### ISSUE THREAD

**Issue by nuthinking** [matt-way/gifuct-js#19]
I started using this great library in conjunction with Giphy (since I don't render their GIFS as plain HTML). In few cases I noted some issues. For example:

- [This one](https://beatflyer-test.s3-eu-west-1.amazonaws.com/bingo-copy.gif) shows artifacts
- [This other](https://media.giphy.com/media/vcnmmtglnhjW6X4Ohj/giphy.gif) has no dims.

Is there any interest in addressing these issues? Should I keep reporting them?

Thanks again for the library!

**Comment by matt-way** [comment]
I'll look into them when I get the chance next. Just had a baby so going to be at least a week I reckon. Any hints as to what you think the problem is, or able to elaborate a bit more?

**Comment by nuthinking** [comment]
@matt-way congratulations! 🎉

No idea, to be honest. But I will keep an eye to see if I spot some patterns. Maybe checking the author to see which tool was used to generate them.

**Comment by nuthinking** [comment]
Will post here some other examples, if you don't mind. You can test them [here](https://codesandbox.io/s/bold-sea-6pkt2?file=/src/App.js:0-3805) too. I make a `Spritesheet` out of them.

[xxYAxDqPhYd7wKtWss](https://media.giphy.com/media/xxYAxDqPhYd7wKtWss/giphy.gif):
![download](https://user-images.githubusercontent.com/163635/107966814-a9dfb300-6fac-11eb-9849-9929cf5543bd.png)

**Comment by nuthinking** [comment]
FYI I tested them with `libgif-js` and it extracted the data correctly without glitches.

**Comment by jeetiss** [comment]
I've experienced the some problem and this is looks like some frames patch previous. @matt-way do you have any idea why it happens and how to detect this special frames?


https://user-images.githubusercontent.com/6726016/108091573-e551ae80-708c-11eb-8380-fde9987de8e6.mov

**Comment by matt-way** [comment]
@nuthinking Does the added disposal check in the demo renderer (by @jeetis) solve your issue? As I mentioned in the PR, this lib is more about the parsing than the rendering. While a better renderer demo is ideal, it is up to the lib user to roll their own.

**Comment by nuthinking** [comment]
@matt-way I didn't realize I have to maintain another context during the rendering. I will check and confirm. Thanks!

**Comment by nuthinking** [comment]
Looks like this fixed it for me. Thanks and sorry for the false alarm!

https://user-images.githubusercontent.com/163635/108524781-b11a0000-72cf-11eb-8432-b5d217c501a2.mp4

**Comment by nuthinking** [comment]
@matt-way remains the `dims` issue with [this GIF](https://media.giphy.com/media/vcnmmtglnhjW6X4Ohj/giphy.gif).

**Comment by jeetiss** [comment]
@nuthinking this is not the `dims` problem
this GIF have local color table with 16 colors on first frame and image data that fills with `16`
and this color is transparent on that frame

strange situation

<img width="484" alt="Снимок экрана 2021-02-23 в 16 13 38" src="https://user-images.githubusercontent.com/6726016/108849348-1d0fa780-75f3-11eb-888c-9462f11a02b7.png">

rendered first frame:
<img width="304" alt="Снимок экрана 2021-02-23 в 16 11 14" src="https://user-images.githubusercontent.com/6726016/108849769-9909ef80-75f3-11eb-9755-dac723520b2c.png">

**Comment by nuthinking** [comment]
I can confirm 2.1.1 fixes this issue. Thanks @jeetiss for the fix and @matt-way for the release 🙌
