### ISSUE TITLE
Build a gif.

### ISSUE THREAD

**Issue by YeisonVelez11** [matt-way/gifuct-js#3]
Your library is great, I have managed to get the frames of a gif. I would like to merge these frames How can I generate a gif from these frames and adding other frames from another gif?

**Comment by matt-way** [comment]
Thanks. Unfortunately I only built this as a *decoder*, without any encoding features. I quickly looked, and there is this library: https://github.com/jnordberg/gif.js/ which you could use to take the frames from gifuct and make a new gif.

Maybe you could make a library that puts this one and that one together.

**Comment by YeisonVelez11** [comment]
These libraries do not seem to be compatible. If I put yours, the other does not work, vice versa. XD

**Comment by andrejpavlovic** [comment]
I've put together a function to convert the frame patches to standalone <img> objects. It does proper merging by taking into account disposal type. Seems to work for all GIFs I've tried so far.

https://gist.github.com/andrejpavlovic/b857e73887104ccc0bb71988573025b0
