### ISSUE TITLE
How to get Netscape block for looping?

### ISSUE THREAD

**Issue by 3400442579** [matt-way/gifuct-js#33]

**Comment by matt-way** [comment]
I don't really understand your question. Are you able to elaborate?

**Comment by 3400442579** [comment]
Gif play times

repeat count, -1 = no repeat, 0 = forever

How to repeat ?

**Comment by matt-way** [comment]
This data should be in the application extension block (if applicable to the gif). You can read more about it here: http://www.matthewflickinger.com/lab/whatsinagif/bits_and_bytes.asp#application_extension_block
