### ISSUE TITLE
Background not removed on first frame

### ISSUE THREAD

**Issue by nuthinking** [matt-way/gifuct-js#34]
I don't know if this is a problem with the demo code, but if you load the gif [https://media0.giphy.com/media/nvKjkfWIl2msw/giphy.gif](https://media0.giphy.com/media/nvKjkfWIl2msw/giphy.gif)

<img src="https://media0.giphy.com/media/nvKjkfWIl2msw/giphy.gif" width="200" height="auto" />

 into the [demo](http://matt-way.github.io/gifuct-js/) (and you make the canvas background colored), you can see that a frame (the first one) has a white background instead of transparent. In the following video I try a few times to stop at the right frame, at the end I succeed.

https://user-images.githubusercontent.com/163635/115850609-56636880-a426-11eb-9c0d-2d7792dd934b.mp4

In my app which uses the same logic as the demo, when I create a texture for my animation I get indeed the white background on the first frame.

![Screenshot 2021-04-23 at 11 24 52](https://user-images.githubusercontent.com/163635/115850850-96c2e680-a426-11eb-8a59-74e4dc75f17d.png)

When the gif is loaded in the browser or in Slack, for instance, no frame has white background.

**Comment by nuthinking** [comment]
This gif is causing an error on my app maybe for other reasons. Something I notice though, is that unlike other gifs, each decompressed frame has an `application` node:

![Screenshot 2021-04-23 at 11 45 09](https://user-images.githubusercontent.com/163635/115853762-cf17f400-a429-11eb-8d0d-232a83de1212.png)

Not sure if this is helpful.

**Comment by jeetiss** [comment]
I have some problem here https://github.com/matt-way/gifuct-js/issues/30

and i have ugly fix for that problem, just check https://github.com/jeetiss/react-gifs/blob/main/src/parse-generate.js#L16-L28

**Comment by nuthinking** [comment]
Fixing this also fixed the error in my rendering 🤷‍♂️ Thanks @jeetiss! 🙌

**Comment by nuthinking** [comment]
Duplicate of #30
