### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by SeanHayes** [matt-way/gifuct-js#4]
Would it be possible to release on npm?

**Comment by Benraay** [comment]
Hi,
You made a great Job getting this working ! I got it working fine with the demo gif and some others but I don't know why it's not working with this attached gif file the first frame is ok but the second and the third images are wrong it look like there is a coordinates shifting on the pixels

I attached the generated spriteSheet 

![pub](https://user-images.githubusercontent.com/734553/41260961-f3f4c002-6dd9-11e8-9abb-5d4040622190.gif)

![capture-generated-canvas](https://user-images.githubusercontent.com/734553/41261157-b33c0c22-6dda-11e8-8c08-6761513a445a.png)

**Comment by andrejpavlovic** [comment]
`npm install matt-way/gifuct-js --save`

**Comment by matt-way** [comment]
I have updated this repo to a new refactored version, but need to get access to the npm account that originally published. Stay tuned.

**Comment by stagr** [comment]
Ok, great. Please let us know when NPM is up-to-date with the new refactored version.

**Comment by matt-way** [comment]
Version has finally been updated (access finally granted). Sorry for the delay.
